version: '3'

services:
  bot:
    image: special-img
    ports:
      - "3000:3000"
    environment:
      KLAMMERAEFFCHEN_BOTTOKEN: token
      KLAMMERAEFFCHEN_BOTCLIENTID: clientID
      KLAMMERAEFFCHEN_CLIENTSECRET: secret
      KLAMMERAEFFCHEN_SERVERPORT: 3000
      KLAMMERAEFFCHEN_OAUTHREDIRECT: http://localhost:3000/authWithCode.html
      KLAMMERAEFFCHEN_DASHBOARDURI: http://localhost:3000/dashboard.html
    volumes:
      - ./uploads:/app/uploads